POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY3YjlmOGM1NmIwMzMyMDAyYzM2ZDJkZSIsImlhdCI6MTc0MDM5NDE5NCwiZXhwIjoxNzQwMzk3Nzk0fQ.tXd-GtXOs9kbyxCMK0d9eCml_SlxIgUWOfzddMYSdrc

{
  "title": "Testy",
  "author": "yessir",
  "url": "https://google.com",
  "likes": 100
}
###
DELETE http://localhost:3003/api/blogs/67bc3c186f7e503a60878d20
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY3YjlmOGM1NmIwMzMyMDAyYzM2ZDJkZSIsImlhdCI6MTc0MDM5NDE5NCwiZXhwIjoxNzQwMzk3Nzk0fQ.tXd-GtXOs9kbyxCMK0d9eCml_SlxIgUWOfzddMYSdrc


###

POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "root",
    "name": "Superuser",
    "password": "salainen"
}

###
DELETE http://localhost:3003/api/users/67b9f8c56b0332002c36d2de